name: peers_touch_desktop
description: A Peers-Touch desktop application.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  peers_touch_base:
    path: ../client/common/peers_touch_base
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  get: ^4.6.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  intl_translation: ^0.21.0
  logging: ^1.3.0
  get_storage: ^2.1.1
  connectivity_plus: ^7.0.0
  window_manager: ^0.5.1
  equatable: ^2.0.7
  file_picker: ^10.3.6
  http: ^1.6.0
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Bold.ttf
          weight: 700
